{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "fullname" . }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    # nginx config upstream requires https
    # ingress.kubernetes.io/secure-backends: "true"
    # registry needs to increase proxy-body-size
    ingress.kubernetes.io/proxy-body-size: 100m
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    secretName: {{ .Values.ingress.host }}.tls
  rules:
  - host: '{{ .Values.ingress.host }}'
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.http.externalPort }}
        path: /
{{- end }}
